
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  msreserva:
    build:
      context: .
      dockerfile: cmd/msreserva/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./certificates/msreserva/private.key.pem:/app/certs/msreserva/private.key.pem
      - ./certificates/msbilhete/public_key.pem:/app/certs/msbilhete/public_key.pem
      - ./certificates/mspagamento/public_key.pem:/app/certs/mspagamento/public_key.pem
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: on-failure

  mspagamento:
    build:
      context: .
      dockerfile: cmd/mspagamento/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./certificates/mspagamento/private_key.pem:/app/certs/mspagamento/private_key.pem
      - ./certificates/msreserva/public_key.pem:/app/certs/msreserva/public_key.pem
      - ./certificates/msbilhete/public_key.pem:/app/certs/msbilhete/public_key.pem
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: on-failure

  msbilhete:
    build:
      context: .
      dockerfile: cmd/msbilhete/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./certificates/msbilhete/private_key.pem:/app/certs/msbilhete/private_key.pem
      - ./certificates/msreserva/public_key.pem:/app/certs/msreserva/public_key.pem
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: on-failure

volumes:
  rabbitmq_data: